name: Selenium Python Tests

# https://www.youtube.com/watch?v=PkJShW50Z-s
# https://github.com/jimdevops19/SeleniumSeries

on:
  push:
    branches:
      - python_
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x' # Specify the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager undetected_chromedriver

    - name: Download WebDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        sudo apt-get install -y openscad mesa-utils libgl1-mesa-dri xvfb
        wget https://chromedriver.storage.googleapis.com/$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Run Selenium tests
      env:
        DISPLAY: :99
      run: |

        # Start a virtual display for running browser tests
        # Set up environment variables for software rendering
        export DISPLAY=:99
        export LIBGL_ALWAYS_SOFTWARE=1
        export MESA_GL_VERSION_OVERRIDE=3.3
        export MESA_GLSL_VERSION_OVERRIDE=330

        # Start a virtual X server
        sudo apt-get install -y xvfb
        Xvfb :99 -screen 0 1024x768x24 &
        sleep 7  # Give Xvfb some time to start

        # python -m unittest discover Python/selenium_
        # touch Python/selenium_/__init__.py
        # local
        # python3 -m unittest discover -s Python/selenium_ -p local_.py


        python -m unittest discover -s Python/selenium_ -p local_.py
